server.port: 8080
spring:
  application.name: fleetlens
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://host.docker.internal:5432/db_fleetlens}
    username: ${DATASOURCE_USERNAME:fleetlens_user}
    password: ${DATASOURCE_PASSWORD:fleetlens_password}
    driver-class-name: ${DATASOURCE_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: update
app:
  version: @project.version@
  admin:
    firstname: ${ADMIN_FIRSTNAME:Admin}
    lastname: ${ADMIN_LASTNAME:ADMIN}
    email: ${ADMIN_EMAIL:admin@admin.fr}
    password: ${ADMIN_PASSWORD:admin}