server.port: 8080
spring:
  application.name: fleetlens
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://host.docker.internal:5432/db_fleetlens}
    username: ${DATASOURCE_USERNAME:fleetlens_user}
    password: ${DATASOURCE_PASSWORD:fleetlens_password}
    driver-class-name: ${DATASOURCE_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: update
security:
  api-key:
    pepper: c639f1cd89fba35c45c7c9235d3b0fa2
  jwt:
    secret: 1b0263acfc70ac0aa31c39b27bab5db3
    ttl-seconds: 3600
app:
  admin:
    firstname: ${ADMIN_FIRSTNAME:Admin}
    lastname: ${ADMIN_LASTNAME:ADMIN}
    email: ${ADMIN_EMAIL:admin@fleetlens.fr}
    password: ${ADMIN_PASSWORD:admin}