name: Build and Push Docker Image
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            IMAGE_TAG=${GITHUB_REF#refs/tags/}
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fleetlens:${IMAGE_TAG} .
          else
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fleetlens:latest .
          fi
      - name: Push Docker image
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            IMAGE_TAG=${GITHUB_REF#refs/tags/}
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/fleetlens:${IMAGE_TAG}
          else
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/fleetlens:latest
          fi